apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVUXJ6cHlCYWd5QisxZXkvVHQrSFJFNXJlSlFjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSTBNRGd3T0RFek16YzFObG9YRFRNMApNRGd3TmpFek16YzFObG93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0QXVlRGc5eDNQb2dpWjA1SUV6ZE9BWGIzYVk5Rys0aWRySHQKc1JQS2F5NjdjUTd5L1JHQmVRWGNRVm5aTzFzWWxRSHA2TEhyM2tqUFRoeUlxMHpRaWNFaUtzNVNVNGFQYkVFRwp1N3gvTENnOVRMSnYxVGdXbmdyTE16Z3gwbndUTjRwNy9MaVlvd1FnREhGMG5Ub29KaDBPLzh3NitaMzNsMWc2CnhwbG9mZUxvUHE2SlozUnRnNUVQVGRDb25xajFJdzdJNkNTQVdZZkZ6ZXFtMGNGbUxpYXJwcTB4ZDQzd2hiK3kKNGxqellBZEFGNDZYZmo0b243VzdoMlZCMnVRM1hOaTNBZndTVTdBTHY3WGlqSHFLL1NpbWo1SHkxS3M1TW1GKwpSU2hXcVRXWVB3TDZGQUExbGs4bkxreEFNUStYbm5ZSEduMHNJZ04rUjVObTE4T3RnUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVTdJWVRjS3h4N05EVEZiZFNlZmJSSlVtRUdpOHdId1lEVlIwakJCZ3dGb0FVN0lZVGNLeHgKN05EVEZiZFNlZmJSSlVtRUdpOHdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBRDJxcUlsYmVFYnorWkRkYjl3NXlGN0NKdFBNMmx6SUhFbjZ0R0FycnRrOXdBNXcvU25CcjRLTXlJS3laCmY0QS9yOEVZZGwrSTE5L3lKSDNYbTFHcXZjOFdicDJnU01MOXpoWmJhblM0d1pVMVhsOHJMa1VDcVhkdFIzMzUKajM4RkNkcEloMk0wc1E0Z1BoK2svY3RDMkFtNTNnS3prTEc1VldTQU1zUEdFY2NJQmVQQnFpaEV0SElKOFFMZQo1STIxY0U3ekFWanRLTnNpK2xRbGhXS0ZISnQ1bXpvWFcxYjI3TTMrZkpHWUMrTHNDU3FXS1BMb3dnNFVRM2hBCmRDRUM2K213bFZUNkI2bERIMFIyT2w1TU1JM0RvTGc0R0NTZnpSUzl6S2dLalFsME5FeVRaUm5qbUEwdnRaSFMKVXk4amYrTitteUtwM21MMG5XQXJvb0FSckE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.100.27:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: anNVUDZ5MW54YzMzVENtalkrby9MQjlIVjdBeVBzbnBFeVRYWW15VTVscz0K

