apiVersion: v1
kind: Service
metadata:
  name: service-api-cea
spec:
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 3000
  - protocol: TCP
    name: https
    port: 443
    targetPort: 3000
  selector:
    app: api-cea